version: '3.1'

services:

  db:
    container_name: mysql_db
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306

  adminer:
    container_name: adminer-11.3.2
    image: adminer
    restart: always
    ports:
      - 9180:8080

  smtp4dev:
    container_name: smtp4dev-v3
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '9280:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9380:25'
